### ISSUE TITLE
No error is reported during running, but there is no display

### ISSUE THREAD

**Issue by Ouwzhong** [siyandong/CoScan#2]
Hello!
Why I can't load any scenes when I run the code, and there is no any output in gazebo, as shown in the following figure.

![image](https://user-images.githubusercontent.com/41533813/158984661-deaf0798-36e1-4d5f-b47b-6aac4a19a1e4.png)

After waiting for a while, gasebo seems to reset automatically due to no data loading.

The following error output in the terminal `rosrun co_scan co_scan` :

![image](https://user-images.githubusercontent.com/41533813/158986023-a3001d7d-769e-4384-9822-98cb7880a5b6.png)

My environment is:
OpenCV 3.3.1
CGAL-4.10
Octomap （build from [https://github.com/OctoMap/octomap](https://github.com/OctoMap/octomap)）

Looking forward to your replay!
thanks！ ：）

**Comment by siyandong** [comment]
Sorry that you didn’t load a valid scene model. There should be scene model files in the directory of /home/username/.gazebo/models that match the .world file loaded in the .launch file. Please find the attached mp1.zip for the model named mp1. Unzip it in the directory of /home/username/.gazebo/models and then run my scripts you will load the model and start the multi-robot scanning process. 

[mp1.zip](https://github.com/siyandong/CoScan/files/8305809/mp1.zip)

PS: The model file format is defined by ROS. For each scene, there should be a folder that contains a .dae file, a .sdf file, and a .config file. You can convert any mesh model to the .dae format and apply it to Gazebo.

**Comment by Ouwzhong** [comment]
Thanks a lot! 
After I put the `mp1` in `/.gazebo/models`, the scene is successfully loaded! 
![image](https://user-images.githubusercontent.com/41533813/159104215-888685b6-db10-4002-8bdd-e09c8c932f88.png)

But the simulation doesn't seem to work properly. Is the default color of mp1 scene gray? Like this:
![image](https://user-images.githubusercontent.com/41533813/159104596-14a92fde-f156-4290-a93f-04c9deaea582.png)

How can I start the multi-robot scanning process? The server seems to start normally, but there is no change in gazebo. And the terminal `rosrun co_scan co_scan` still fail to connect the server after waiting for a while:
![image](https://user-images.githubusercontent.com/41533813/159104776-1d9d192a-851e-4da7-b6eb-86df9c983ad8.png)

**Comment by siyandong** [comment]
Modify the IP address to your localhost. See if it solves your problem. https://github.com/siyandong/CoScan/blob/68b0adf9ef5fe3b4896f0aa28dd1fdc88021b433/co_scan/src/data_engine.h#L116

**Comment by Ouwzhong** [comment]
I modify the IP address to 
`char *server_ip = "127.0.0.1"; `
or
`char *server_ip = "localhost";`
or 
`char *server_ip = localhost;`
but it still has the same problem.

**Comment by chen12345678910** [comment]
I also encountered the above problem, how to solve it?

**Comment by siyandong** [comment]
Hi guys, if there is a "connecting server... failed" in the terminal, it's a network problem. The code performs a centralized solution, where all the frames and poses from robots are sent to the server from the simulator. Note that the simulator and server are all running locally. 
Specifically, you should first run `roslaunch virtual_scan simulator.launch` to launch the simulator, then run `roslaunch virtual_scan data_sever.launch` to start the server, finally run `rosrun co_scan co_scan` to start the scanning process. I run the code on a virtual machine and set the IP with the local IP address, and it works.

**Comment by Ouwzhong** [comment]
> I also encountered the above problem, how to solve it?

Hello~
I have solved that problem after following @siyandong's advice to modify the ip address in [data_engine.h](https://github.com/siyandong/CoScan/blob/68b0adf9ef5fe3b4896f0aa28dd1fdc88021b433/co_scan/src/data_engine.h#L116). 

**You should also recomplie the source files before continuing.**

In addition, when running the `rosrun` command, the current running directory of the terminal should be `/catkin_ws`, otherwise an error will occur.

![image](https://user-images.githubusercontent.com/41533813/161051197-4b309acc-7311-4768-be4c-4ac3d9e5a9c9.png)

**Comment by Ouwzhong** [comment]
Why doesn't the plan_sync_move_paths window show anything?

![image](https://user-images.githubusercontent.com/41533813/161053002-381e7a01-f5a8-4096-87cf-7752dfa9b2be.png)

**Comment by chen12345678910** [comment]
I have a problem，this page is not displayed（plan sync move paths）
![2022-03-31 21-07-34屏幕截图](https://user-images.githubusercontent.com/73885580/161067751-9ad8bcde-cca4-4487-9ed0-d7cbb08c063b.png)

**Comment by siyandong** [comment]
I think it's a kind of display bug maybe in `cv::imshow` or `cv::waitKey`, and it doesn't affect the scanning process. Check if there are visualization files saved in the ./result folder.

**Comment by Ouwzhong** [comment]
> I have a problem，this page is not displayed（plan sync move paths）

Fortunately, I can get the visual results in the _plan sync move paths_ window.
or you can make a directory to save the results.

![image](https://user-images.githubusercontent.com/41533813/161101858-2eaf9cbf-383e-40e2-808e-c83f1bb058ee.png)

Thanks to @siyandong for helping me solve these problems.

**Comment by Abhishek-002** [comment]
I'm still facing the same issue after doing all these things as advised. Please tell me how to fix this issue
![ss_seg](https://user-images.githubusercontent.com/51160492/164395559-7ef2a09a-16d2-491e-bbea-5f0d4040b8cb.png)
.

**Comment by Abhishek-002** [comment]
please help me out

**Comment by Yangye0526** [comment]
I met the same problem. I changed the ip address in deta.engine.h, but it didn't work. May I ask how you changed the address?
