### ISSUE TITLE
 I also encountered the above problem, how to solve it?

### ISSUE THREAD

**Issue by Abhishek-002** [siyandong/CoScan#3]
> I also encountered the above problem, how to solve it?

Hello~
I have solved that problem after following @siyandong's advice to modify the ip address in [data_engine.h](https://github.com/siyandong/CoScan/blob/68b0adf9ef5fe3b4896f0aa28dd1fdc88021b433/co_scan/src/data_engine.h#L116). 

**You should also recomplie the source files before continuing.**

In addition, when running the `rosrun` command, the current running directory of the terminal should be `/catkin_ws`, otherwise an error will occur.

![image](https://user-images.githubusercontent.com/41533813/161051197-4b309acc-7311-4768-be4c-4ac3d9e5a9c9.png)

_Originally posted by @Ouwzhong in https://github.com/siyandong/CoScan/issues/2#issuecomment-1084498001_

**Comment by Yangye0526** [comment]
I met the same problem. I changed the ip address in deta.engine.h, but it didn't work. May I ask how you changed the address?
