### ISSUE TITLE
IP problem

### ISSUE THREAD

**Issue by Yangye0526** [siyandong/CoScan#4]
I met the same problem. I changed the ip address in deta.engine.h, but it didn't work. May I ask how you changed the address?
![QQ图片20230705163544](https://github.com/siyandong/CoScan/assets/110235486/e7b34745-e7a4-4ad0-924d-457e9b580f0b)
![QQ图片20230705163509](https://github.com/siyandong/CoScan/assets/110235486/93b07603-10b1-498e-b42f-22a6c8003c7d)

**Comment by siyandong** [comment]
Did you re-compile the project? If not, please try to use this command catkin_make_isolated
